apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: docker-spring
spec:                
  selector:         
    matchLabels:
      app: docker-spring
  replicas: 3        
  template:
    metadata:
      labels:        
        app: docker-spring
    spec:
      containers:
        - name: docker-spring
          image: docker-spring
          ports:
            - containerPort: 8080
