apiVersion: v1
kind: Service
metadata:
  name: docker-spring
  labels:
    name: docker-spring
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: docker-spring
  type: NodePort       
